# This file was generated by GoReleaser. DO NOT EDIT.
cask "sandcastle" do
  binary "sandcastle", target: "sc"

  version "0.19.3"

  on_macos do
    on_arm do
      sha256 "a53bd4c0fa74e0c50dbdfae6a9643523408efc931175daff35a9880ce5717704"
      url "https://github.com/thieso2/sandcastle-incus/releases/download/v#{version}/sandcastle-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "e833e55abeab7aaa8ca48217f37f3015f64021dd14cb7545a1b3f68ac4cdb2ea"
      url "https://github.com/thieso2/sandcastle-incus/releases/download/v#{version}/sandcastle-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5d39cc23038ded7d8717375fe530d6f40b514e173ba5aa4889af86c616c3f9a6"
      url "https://github.com/thieso2/sandcastle-incus/releases/download/v#{version}/sandcastle-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "e9a06d9d07d1c62dd946dda6b160c034c1989de985eae9dde41ff9cf7f9f7b33"
      url "https://github.com/thieso2/sandcastle-incus/releases/download/v#{version}/sandcastle-linux-amd64.tar.gz"
    end
  end

  name "sandcastle"
  desc "CLI for Sandcastle — multi-tenant developer sandboxes on Incus"
  homepage "https://github.com/thieso2/sandcastle-incus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sandcastle"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sandcastle"]
    end
  end

  # No zap stanza required
end
