# This file was generated by GoReleaser. DO NOT EDIT.
cask "sandcastle" do
  binary "sandcastle", target: "sc"

  version "0.16.13"

  on_macos do
    on_arm do
      sha256 "1e08ededa5c01c80b2eb4dc8a21a05d89eb663d5e876991793bcba072a01e563"
      url "https://github.com/thieso2/sandcastle-incus/releases/download/v#{version}/sandcastle-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "dcfd0d1288991725f6b91bba3104cddbd654ae25842d20c96b5bf7b3d18f3c12"
      url "https://github.com/thieso2/sandcastle-incus/releases/download/v#{version}/sandcastle-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c5d0a193f073b2b6d185851e79f12e749350af98e92140a30e6a53b87ca26361"
      url "https://github.com/thieso2/sandcastle-incus/releases/download/v#{version}/sandcastle-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "7b1efa29c35e4f616dacd8a093a97b9d9a10e38c46a4351893ca97d18fbe9dea"
      url "https://github.com/thieso2/sandcastle-incus/releases/download/v#{version}/sandcastle-linux-amd64.tar.gz"
    end
  end

  name "sandcastle"
  desc "CLI for Sandcastle — multi-tenant developer sandboxes on Incus"
  homepage "https://github.com/thieso2/sandcastle-incus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sandcastle"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sandcastle"]
    end
  end

  # No zap stanza required
end
