# This file was generated by GoReleaser. DO NOT EDIT.
cask "sandcastle" do
  binary "sandcastle", target: "sc"

  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "de60bb643a5a2afff265c4fed0f307a10cdbfaaac3b4c05ac8787f2024a3341f"
      url "https://github.com/thieso2/sandcastle-incus/releases/download/v#{version}/sandcastle-darwin-amd64.tar.gz",
        verified: "github.com/thieso2/sandcastle-incus/"
    end
    on_arm do
      sha256 "ee465ef256f82d9984205695c393e96cd88af895eaa733368b69be066f90418c"
      url "https://github.com/thieso2/sandcastle-incus/releases/download/v#{version}/sandcastle-darwin-arm64.tar.gz",
        verified: "github.com/thieso2/sandcastle-incus/"
    end
  end

  on_linux do
    on_intel do
      sha256 "031ec11e423a7eebe81ea9e693f28c5631dc6bb003ebbc95253b19b2e822c9a5"
      url "https://github.com/thieso2/sandcastle-incus/releases/download/v#{version}/sandcastle-linux-amd64.tar.gz",
        verified: "github.com/thieso2/sandcastle-incus/"
    end
    on_arm do
      sha256 "774b4ea66b37ba4faa2881b6d78a51f9566672d38b7fa407bc7f4c1015232187"
      url "https://github.com/thieso2/sandcastle-incus/releases/download/v#{version}/sandcastle-linux-arm64.tar.gz",
        verified: "github.com/thieso2/sandcastle-incus/"
    end
  end

  name "sandcastle"
  desc "CLI for Sandcastle — multi-tenant developer sandboxes on Incus"
  homepage "https://github.com/thieso2/sandcastle-incus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sandcastle"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sandcastle"]
    end
  end

  # No zap stanza required

end
