# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cio < Formula
  desc "Fast Go CLI for Google Cloud Storage and BigQuery"
  homepage "https://github.com/thieso2/cio"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thieso2/cio/releases/download/v0.1.0/cio_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "1a96755df16032daba9c69f068a1901a0dae52ade9dba5f5a50d5ad8afddf9be"

      define_method(:install) do
        bin.install "cio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thieso2/cio/releases/download/v0.1.0/cio_0.1.0_Darwin_arm64.tar.gz"
      sha256 "017ca59ad28473733eb82390be49225a488cd1011dfaaf70b6dd32dc4143697a"

      define_method(:install) do
        bin.install "cio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thieso2/cio/releases/download/v0.1.0/cio_0.1.0_Linux_x86_64.tar.gz"
      sha256 "195e94677c60db0a8d0867e15e3a86852525da7d1bf65329463183ff851cdfdb"
      define_method(:install) do
        bin.install "cio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thieso2/cio/releases/download/v0.1.0/cio_0.1.0_Linux_arm64.tar.gz"
      sha256 "f103f104e7718015843cdcd1813e20896f1888dc930badd3c5acce235a11e186"
      define_method(:install) do
        bin.install "cio"
      end
    end
  end

  test do
    system "#{bin}/cio", "--version"
  end
end
