# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cio < Formula
  desc "Fast Go CLI for Google Cloud Storage and BigQuery"
  homepage "https://github.com/thieso2/cio"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thieso2/cio/releases/download/v0.1.5/cio_0.1.5_Darwin_x86_64.tar.gz"
      sha256 "c89ea6365c8e2b3f1a2d9b6a89f1da08aff92446604a28bfc9c4c2d40a34db55"

      define_method(:install) do
        bin.install "cio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thieso2/cio/releases/download/v0.1.5/cio_0.1.5_Darwin_arm64.tar.gz"
      sha256 "0aebfa21d41af7621bc3a8db379b0f21ce7ddb7a4880bd3c4ff8821fa1cb0c64"

      define_method(:install) do
        bin.install "cio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thieso2/cio/releases/download/v0.1.5/cio_0.1.5_Linux_x86_64.tar.gz"
      sha256 "0c614d73151bcac09bbfb2cd2980c0a51565187f11d5704f22da08469db430a0"
      define_method(:install) do
        bin.install "cio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thieso2/cio/releases/download/v0.1.5/cio_0.1.5_Linux_arm64.tar.gz"
      sha256 "fc8e9781fb39e0c6f5f2def40f10fdabfa697bb07ed94395e0fb8823c447a797"
      define_method(:install) do
        bin.install "cio"
      end
    end
  end

  test do
    system "#{bin}/cio", "--version"
  end
end
