# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cio < Formula
  desc "Fast Go CLI for Google Cloud Storage and BigQuery"
  homepage "https://github.com/thieso2/cio"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thieso2/cio/releases/download/v0.2.0/cio_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "e85d3d147689525c4c360bb2c1ea33293aeb93f33d24e1d784fca618762db07e"

      define_method(:install) do
        bin.install "cio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thieso2/cio/releases/download/v0.2.0/cio_0.2.0_Darwin_arm64.tar.gz"
      sha256 "bda29d40efd994a58cce265dbcf7225f9513741b022ebc0ffb7f5f3e6c1b0f61"

      define_method(:install) do
        bin.install "cio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thieso2/cio/releases/download/v0.2.0/cio_0.2.0_Linux_x86_64.tar.gz"
      sha256 "fb040b2196f0811ec2a145af1b51042e98837a9849789651bba5c7c6486356b8"
      define_method(:install) do
        bin.install "cio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thieso2/cio/releases/download/v0.2.0/cio_0.2.0_Linux_arm64.tar.gz"
      sha256 "46ed69f164b543509fca70aa6ee8e46d52fb6a2d8442eb1a62457ff7465e94a2"
      define_method(:install) do
        bin.install "cio"
      end
    end
  end

  test do
    system "#{bin}/cio", "--version"
  end
end
