# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sandcastle < Formula
  desc "CLI for Sandcastle, a self-hosted shared Docker sandbox platform"
  homepage "https://github.com/thieso2/Sandcastle"
  version "0.8.118"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thieso2/Sandcastle/releases/download/v0.8.118/sandcastle-darwin-amd64.tar.gz"
      sha256 "9d52c22eff64e56b9394ec5686d4ada802c81a2b076cb58664e2c682c1f87ee4"

      define_method(:install) do
        bin.install "sandcastle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thieso2/Sandcastle/releases/download/v0.8.118/sandcastle-darwin-arm64.tar.gz"
      sha256 "1164afbfd83bd79bfb7f857e65225bc1ad7644931fec14999c9c196d00adcb02"

      define_method(:install) do
        bin.install "sandcastle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thieso2/Sandcastle/releases/download/v0.8.118/sandcastle-linux-amd64.tar.gz"
      sha256 "71b36f222e8b299c644dcfb3675e1dede452943cacf0c7040f4041497b81b440"
      define_method(:install) do
        bin.install "sandcastle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thieso2/Sandcastle/releases/download/v0.8.118/sandcastle-linux-arm64.tar.gz"
      sha256 "21b409b27f2304d4975935a7ec8cdd4da6ddc77c12af1b1b85e710f4c6be9a83"
      define_method(:install) do
        bin.install "sandcastle"
      end
    end
  end

  test do
    system "#{bin}/sandcastle", "version"
  end
end
