# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sandcastle < Formula
  desc "CLI for Sandcastle, a self-hosted shared Docker sandbox platform"
  homepage "https://github.com/thieso2/Sandcastle"
  version "0.8.143"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thieso2/Sandcastle/releases/download/v0.8.143/sandcastle-darwin-amd64.tar.gz"
      sha256 "5c75418a813e84896b40b8833634a6fc8e9e1f8eda7394b26e6a47032c4a5acb"

      define_method(:install) do
        bin.install "sandcastle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thieso2/Sandcastle/releases/download/v0.8.143/sandcastle-darwin-arm64.tar.gz"
      sha256 "46ab5da61b4fe988d18d4d185be4899a60aea4e4a368688e62c67c34a01f256a"

      define_method(:install) do
        bin.install "sandcastle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thieso2/Sandcastle/releases/download/v0.8.143/sandcastle-linux-amd64.tar.gz"
      sha256 "1d1c0aa6ac95609eb00862d07729c8a13a1da57dfbc8864708b3b08bd56940cd"
      define_method(:install) do
        bin.install "sandcastle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thieso2/Sandcastle/releases/download/v0.8.143/sandcastle-linux-arm64.tar.gz"
      sha256 "e5f0e09e933688e7bcc4808570638da0b2981fd5debcabb3a4277c1703759d34"
      define_method(:install) do
        bin.install "sandcastle"
      end
    end
  end

  test do
    system "#{bin}/sandcastle", "version"
  end
end
