# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sandcastle < Formula
  desc "CLI for Sandcastle, a self-hosted shared Docker sandbox platform"
  homepage "https://github.com/thieso2/Sandcastle"
  version "0.8.56"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thieso2/Sandcastle/releases/download/v0.8.56/sandcastle-darwin-amd64.tar.gz"
      sha256 "6cf6dc7125843c8b058f74b7cdd36efcf312fb12cf5f37626814578891d69ac9"

      define_method(:install) do
        bin.install "sandcastle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thieso2/Sandcastle/releases/download/v0.8.56/sandcastle-darwin-arm64.tar.gz"
      sha256 "ae41483c80fa6e6193c9075df246f259ca1359d3953577d6ebdd0d2cb5d21b43"

      define_method(:install) do
        bin.install "sandcastle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thieso2/Sandcastle/releases/download/v0.8.56/sandcastle-linux-amd64.tar.gz"
      sha256 "ff83c7708b992330c2632740e8f0c55c097b5899298b997e7f30aa5a792190b1"
      define_method(:install) do
        bin.install "sandcastle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thieso2/Sandcastle/releases/download/v0.8.56/sandcastle-linux-arm64.tar.gz"
      sha256 "a8ca44d4afe5c51e4ec26f42ee0112339ac3a39de6716267a98a810cb4b4ea1d"
      define_method(:install) do
        bin.install "sandcastle"
      end
    end
  end

  test do
    system "#{bin}/sandcastle", "version"
  end
end
