# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sandcastle < Formula
  desc "CLI for Sandcastle, a self-hosted shared Docker sandbox platform"
  homepage "https://github.com/thieso2/Sandcastle"
  version "0.8.49"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thieso2/Sandcastle/releases/download/v0.8.49/sandcastle-darwin-amd64.tar.gz"
      sha256 "e843d5735483036e289b186e7e22bcc5426fdcfda12fda887c463b7be840f769"

      define_method(:install) do
        bin.install "sandcastle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thieso2/Sandcastle/releases/download/v0.8.49/sandcastle-darwin-arm64.tar.gz"
      sha256 "64d9d551e45a48d860582af08d86e849ddaf18fc4d261e6af7e9ac1d0407a755"

      define_method(:install) do
        bin.install "sandcastle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thieso2/Sandcastle/releases/download/v0.8.49/sandcastle-linux-amd64.tar.gz"
      sha256 "e3dc6a9c9f6f75274de806290795144b01e4ba0149c9614f6f260d27f6d3f533"
      define_method(:install) do
        bin.install "sandcastle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thieso2/Sandcastle/releases/download/v0.8.49/sandcastle-linux-arm64.tar.gz"
      sha256 "e715c223e12706ece7661c1576a4ed950c697b0a0269807a439bae02e4290a92"
      define_method(:install) do
        bin.install "sandcastle"
      end
    end
  end

  test do
    system "#{bin}/sandcastle", "version"
  end
end
